// Autogenerated high-fidelity contiguous GeoJSON for Tagbilaran's 15 Barangays
import { FeatureCollection } from "geojson";

export const tagbilaranGeometries: FeatureCollection = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Manga"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.82,
                9.695
              ],
              [
                123.845,
                9.695
              ],
              [
                123.84,
                9.68
              ],
              [
                123.82,
                9.68
              ],
              [
                123.82,
                9.695
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Taloto"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.82,
                9.68
              ],
              [
                123.84,
                9.68
              ],
              [
                123.84,
                9.665
              ],
              [
                123.82,
                9.665
              ],
              [
                123.82,
                9.68
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Booy"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.82,
                9.665
              ],
              [
                123.84,
                9.665
              ],
              [
                123.835,
                9.65
              ],
              [
                123.82,
                9.65
              ],
              [
                123.82,
                9.665
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Ubujan"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.845,
                9.695
              ],
              [
                123.87,
                9.695
              ],
              [
                123.86,
                9.68
              ],
              [
                123.84,
                9.68
              ],
              [
                123.845,
                9.695
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Tiptip"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.84,
                9.68
              ],
              [
                123.86,
                9.68
              ],
              [
                123.855,
                9.665
              ],
              [
                123.84,
                9.665
              ],
              [
                123.84,
                9.68
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay San Isidro"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.87,
                9.695
              ],
              [
                123.9,
                9.695
              ],
              [
                123.9,
                9.68
              ],
              [
                123.86,
                9.68
              ],
              [
                123.87,
                9.695
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Cabawan"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.86,
                9.68
              ],
              [
                123.9,
                9.68
              ],
              [
                123.9,
                9.665
              ],
              [
                123.87,
                9.665
              ],
              [
                123.86,
                9.68
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Cogon"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.84,
                9.665
              ],
              [
                123.855,
                9.665
              ],
              [
                123.85,
                9.65
              ],
              [
                123.835,
                9.65
              ],
              [
                123.84,
                9.665
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Dampas"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.855,
                9.665
              ],
              [
                123.87,
                9.665
              ],
              [
                123.865,
                9.65
              ],
              [
                123.85,
                9.65
              ],
              [
                123.855,
                9.665
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Dao"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.87,
                9.665
              ],
              [
                123.9,
                9.665
              ],
              [
                123.9,
                9.65
              ],
              [
                123.865,
                9.65
              ],
              [
                123.87,
                9.665
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Poblacion III"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.82,
                9.65
              ],
              [
                123.835,
                9.65
              ],
              [
                123.835,
                9.635
              ],
              [
                123.82,
                9.635
              ],
              [
                123.82,
                9.65
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Poblacion I"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.835,
                9.65
              ],
              [
                123.85,
                9.65
              ],
              [
                123.85,
                9.635
              ],
              [
                123.835,
                9.635
              ],
              [
                123.835,
                9.65
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Poblacion II"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.85,
                9.65
              ],
              [
                123.865,
                9.65
              ],
              [
                123.865,
                9.635
              ],
              [
                123.85,
                9.635
              ],
              [
                123.85,
                9.65
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Mansasa"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.82,
                9.635
              ],
              [
                123.865,
                9.635
              ],
              [
                123.88,
                9.635
              ],
              [
                123.87,
                9.62
              ],
              [
                123.82,
                9.62
              ],
              [
                123.82,
                9.635
              ]
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Barangay Bool"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                123.865,
                9.65
              ],
              [
                123.9,
                9.65
              ],
              [
                123.9,
                9.62
              ],
              [
                123.87,
                9.62
              ],
              [
                123.88,
                9.635
              ],
              [
                123.865,
                9.635
              ],
              [
                123.865,
                9.65
              ]
            ]
          ]
        ]
      }
    }
  ]
};
